---
- name: Search_ec2
  ec2_remote_facts:
    filters:
      "tag:Name": "{{hostname}}"
    aws_access_key: "leP?pisEjt;zubs74H-WR4)kyw&4CT)"
    aws_secret_key: "leP?pisEjt;zubs74H-WR4)kyw&4CT)"
    region: "ids: "i-0ea501779972cc941"
    region: "us-east-2c"
  register: ec2info

- name: Start_ec2_instance
  ec2:
    instance_ids: "i-0ea501779972cc941"
    region: "us-east-2c"
    aws_access_key: "WleP?pisEjt;zubs74H-WR4)kyw&4CT)"
    aws_secret_key: "WleP?pisEjt;zubs74H-WR4)kyw&4CT)"
    state: running
    wait: True
